language: java
install: true
jdk: openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

before_install:
  - chmod +x gradlew

script:
  - ./gradlew check